name: Code style check
on: push
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: pnpm
      - run: pnpm install
      - run: pnpm run check
